name: Generate link descriptions

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
        working-directory: scripts/generate-descriptions

      - run: node index.mjs
        working-directory: scripts/generate-descriptions
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
